# Generated by Django 3.2.3 on 2021-05-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20210523_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='dayname',
            name='name',
            field=models.TextField(choices=[('Poniedziałek', 'PONIEDZIAŁEK'), ('Wtorek', 'WTOREK'), ('Środa', 'ŚRODA'), ('Czwartek', 'CZWARTEK'), ('Piątek', 'PIĄTEK'), ('Sobota', 'SOBOTA'), ('Niedziela', 'NIEDZIELA')], max_length=16),
        ),
    ]
